version: "3.9"
   
services:
  web: 
    build: .
    ports: 
      - "8080:3000"
    environment: 
      - GRAPHQL_ADMIN_SECRET=myadminsecretkey
      - GRAPHQL_URL=https://rurich-graphql-server.herokuapp.com/v1/graphql
      - AUTH_TOKEN=leLvvwyorNdFjbeAfVQxGuTJgUbsxc
      - COOKIE_SECRET=grYCuerNAVDGVttphyyooupFFkqTDK
      - REDIS_URL=redis://default:redispw@redis:6379
  worker:
    build:
      context: .
      dockerfile: workers/Dockerfile
    ports: 
      - "8000:8000"
    environment:
      - REDIS_URL=redis://default:redispw@redis:6379
  redis:
    image: redis
    ports: 
      - "6379:6379"
    volumes: 
      - cache:/data
    environment:
      - REDIS_PASSWORD=redispw
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: goares
  postgres:
    image: postgres
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.12.0
    ports:
    - "8081:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@db:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
    driver: local
  cache:
    driver: local