table:
  name: episodes
  schema: public
object_relationships:
  - name: season
    using:
      foreign_key_constraint_on: season_id
select_permissions:
  - role: readonly
    permission:
      columns:
        - episode_number
        - description
        - title
        - id
        - season_id
      filter: {}
      allow_aggregations: true
