table:
  name: characters
  schema: public
object_relationships:
  - name: show
    using:
      foreign_key_constraint_on: show_id
select_permissions:
  - role: readonly
    permission:
      columns:
        - first_name
        - image_url
        - last_name
        - id
        - show_id
      filter: {}
      allow_aggregations: true
