table:
  name: auth_users
  schema: public
array_relationships:
  - name: auth_sessions
    using:
      foreign_key_constraint_on:
        column: user_id
        table:
          name: auth_sessions
          schema: public
