- name: allowed-queries
  definition:
    queries:
      - name: Delete Auth User by Email
        query: |
          mutation DeleteTestUser ($_eq: String!) {
            delete_auth_users(where: {email:{_eq:$_eq}}) {
              affected_rows
            }
          }
      - name: Get Show Data
        query: |
          query ShowsData ($id: uuid!) {
            shows_by_pk(id: $id) {
              characters_aggregate {
                aggregate {
                  count
                }
                nodes {
                  first_name
                  last_name
                  image_url
                }
              }
              seasons_aggregate {
                aggregate {
                  count
                }
                nodes {
                  id
                  season_number
                  episodes_aggregate {
                    aggregate {
                      count
                    }
                    nodes {
                      id
                      episode_number
                      title
                      description
                    }
                  }
                }
              }
            }
          }
      - name: Get All Shows
        query: |
          query GetShows {
            shows(limit: 1000) {
              id
              show_name
            }
          }
