- comment: ""
  definition:
    query:
      collection_name: allowed-queries
      query_name: Delete Auth User by Email
  methods:
    - DELETE
  name: Delete Auth User by Email
  url: :_eq
- comment: ""
  definition:
    query:
      collection_name: allowed-queries
      query_name: Get Show Data
  methods:
    - GET
  name: Get Show Data
  url: show/:id
- comment: Lists all shows
  definition:
    query:
      collection_name: allowed-queries
      query_name: Get All Shows
  methods:
    - GET
  name: Get All Shows
  url: shows
