name: Build, push, and deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push request on the main branch for changes in the specified paths.
  push:
    branches:
      - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build".
  build:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
    - name: Checkout master
      uses: actions/checkout@main

    # Install doctl.
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    # Build a Docker image of your application in your registry and tag the image with the $GITHUB_SHA.
    - name: Build container image
      run: docker build -t ${{ secrets.REGISTRY_NAME }}/app .
    
    - name: Tag container as latest
      run: docker tag ${{ secrets.REGISTRY_NAME }}/app ${{ secrets.REGISTRY_NAME }}/app:latest
    
    - name: Tag container with $GITHUB_SHA.
      run: docker tag ${{ secrets.REGISTRY_NAME }}/app ${{ secrets.REGISTRY_NAME }}/app:$(echo $GITHUB_SHA | head -c7)
    
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    - name: Push image to DigitalOcean Container Registry
      run: docker push --all-tags ${{ secrets.REGISTRY_NAME }}/app